openapi: 3.0.0
info:
  title: Transaction System API
  version: 1.0.0
servers:
- url: http://localhost:8000
paths:
  /transaction:
    post:
      summary: Создание новой транзакции
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/transaction_body'
        required: true
      responses:
        "200":
          description: Транзакция успешно создана
  /transaction/{id}:
    get:
      summary: Получение информации о транзакции
      parameters:
      - name: id
        in: path
        description: Идентификатор транзакции
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Информация о транзакции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/transaction_response'
        "404":
          description: Транзакция не найдена
components:
  schemas:
    transaction_body:
      type: object
      properties:
        amount:
          type: number
          description: Сумма транзакции
        currency:
          type: string
          description: Аббревиатура валюты
        sender_card_number:
          type: string
          minLength: 16
          maxLength: 16
          description: Номер банковской карты отправителя
        recipient_phone_number:
          type: string
          minLength: 11
          maxLength: 11
          description: Номер телефона получателя
    transaction_response:
      type: object
      properties:
        amount:
          type: number
          description: Сумма транзакции
        currency:
          type: string
          description: Аббревиатура валюты
        sender_card_number:
          type: string
          description: Номер банковской карты отправителя
        recipient_phone_number:
          type: string
          description: Номер телефона получателя
        date_time:
          type: string
          format: date-time
          description: Дата и время проведения транзакции
